export const ui = {
  nav: {
    home: "Home",
    projects: "Projects",
    gameLab: "Game Lab",
    lore: "Lore",
    toolbox: "Toolbox",
    contact: "Contact",
  },
  modes: {
    recruiter: "Recruiter Mode",
    themeLight: "Use light theme",
    themeDark: "Use dark theme",
  },
  home: {
    introTitle: "Games, systems, and the long way around.",
    introLabel: "SAVE FILE 01 · CURRENTLY ONLINE",
    gameLabCasual: "Things I’m playing with, breaking, and slowly making playable.",
    gameLabDirect: "Selected game-development work, current scope, and technical direction.",
    softwareCasual: "Useful software born from very specific problems.",
    softwareDirect: "Selected software projects, responsibilities, and core technologies.",
  },
  common: {
    menu: "Menu",
    close: "Close",
    details: "Open case file",
    github: "GitHub",
    linkedin: "LinkedIn",
    source: "Source",
    live: "Open live project",
    devlog: "Read devlog",
    copy: "Copy command",
    copied: "Copied",
  },
} as const;
